export const person = [{
       id: 1,
       name: "Renata",
       age: 30,
       city: "Amsterdam",
       country: "Netherlands",
       email: "renata@gmail.com",
       url: 'http://res.cloudinary.com/dngl5axlu/image/upload/c_scale,h_350/v1529588336/samples/people/kitchen-bar.jpg',
       interests: [ 'yoga', 'food', 'museums', 'drinking', 'fishing' ],
       isTraveler: true,

   },
   {
       id: 2,
       name: "Cris",
       age: 35,
       city: "Berlin",
       country: "Germany",
       email: "cris@gmail.com",
       url: 'http://res.cloudinary.com/dngl5axlu/image/upload/c_scale,h_350/v1529588340/samples/people/smiling-man.jpg',
       interests: [ 'yoga', 'food', 'museums','sport', 'books', 'drinking' ],
       isTraveler: true,

   },
   {
       id: 3,
       name: "Rodrigo",
       age: 36,
       city: "Brussels",
       country: "Belgium",
       email: "rodrigo@gmail.com",
       url: 'http://res.cloudinary.com/dngl5axlu/image/upload/c_scale,h_350/v1529588345/samples/people/bicycle.jpg',
       interests: [ 'yoga', 'dancing', 'sport' ],
       isTraveler: true,

   },
   {
     id: 4,
     name: "Ana",
     age: 30,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "ana@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529604393/samples/bike.jpg',
     interests: [ 'museums', 'yoga', 'fishing' ],
     isTraveler: true,

   },
   {
     id: 5,
     name: "Antonia",
     age: 50,
     city: "Paris",
     country: "France",
     email: "antonia@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529604395/samples/people/jazz.jpg',
     interests: [ 'museums', 'coffee', 'books' ],
     isTraveler: true,

   },
   {
     id: 6,
     name: "Marcia",
     age: 50,
     city: "Stockolm",
     country: "Sweden",
     email: "marcia@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611316/pexels-photo-733872.jpg',
     interests: [ 'coffee', 'museums', 'yoga' ],
     isTraveler: true,

   },
   {
     id: 7,
     name: "Carlos",
     age: 57,
     city: "Berlin",
     country: "Germany",
     email: "carlos@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529604391/samples/people/smiling-man.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: true,

   },
   {
     id: 8,
     name: "Gilberto",
     age: 55,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "gilberto@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529610806/LYB_People_Profile_2808_29.jpg',
     interests: [ 'drinking', 'books', 'museums' ],
     isTraveler: true,

   },
   {
     id: 9,
     name: "Junior",
     age: 34,
     city: "Paris",
     country: "France",
     email: "junior@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611448/paramount-35065-Full-Image_GalleryBackground-en-US-1483994508505._RI_SX940_.jpg',
     interests: [ 'drinking', 'museums', 'hicking' ],
     isTraveler: true,

   },
   {
     id: 10,
     name: "Aline",
     age: 33,
     city: "Berlin",
     country: "Germany",
     email: "aline@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611922/09zali07-vyl3e5b2-12.06.27-ast_ft_female-travel-4263023499-1.jpg',
     interests: [ 'hicking', 'yoga', 'coffee' ],
     isTraveler: true,

   },
   {
     id: 11,
     name: "Luiz",
     age: 59,
     city: "Stockolm",
     country: "Sweden",
     email: "luiz@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612239/depositphotos_164070086-stock-photo-excited-old-man-traveling-in.jpg',
     interests: [ 'hicking', 'yoga', 'coffee' ],
     isTraveler: true,

   },
   {
     id: 12,
     name: "Antonio",
     age: 29,
     city: "Paris",
     country: "France",
     email: "antonio@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612364/862-05998281en_Masterfile.jpg',
     interests: [ 'fishing', 'books', 'dancing' ],
     isTraveler: false,

   },
   {
     id: 13,
     name: "Aparecido",
     age: 56,
     city: "Brussels",
     country: "Belgium",
     email: "aparecido@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612558/man_travelling_alone_city.jpg',
     interests: [ 'hicking', 'yoga', 'coffee' ],
     isTraveler: false,

   },
   {
     id: 14,
     name: "Camila",
     age: 23,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "camila@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612685/o-WOMAN-TRAVEL-facebook.jpg',
     interests: [ 'hicking', 'yoga', 'coffee' ],
     isTraveler: false,

   },
   {
     id: 15,
     name: "Carla",
     age: 27,
     city: "Paris",
     country: "France",
     email: "carla@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612801/57c98588170000012ac7737c.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 16,
     name: "Denis",
     age: 29,
     city: "Berlin",
     country: "Germany",
     email: "denis@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529613027/95063650-senior-happy-european-woman-and-man-travelling-together-walking-with-baggage-on-city.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 17,
     name: "Tiago",
     age: 30,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "tiago@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529614252/travel-man.jpg',
     interests: [ 'sport', 'books', 'drinking' ],
     isTraveler: false,

   },
   {
     id: 18,
     name: "Janne",
     age: 35,
     city: "Stockolm",
     country: "Sweden",
     email: "janne@gmail.com",
     url: 'https://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529613951/Berlin-Travel-Bucket-List-9-700x432.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 19,
     name: "Loize",
     age: 36,
     city: "Paris",
     country: "France",
     email: "loize@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529614432/n05a7352.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 20,
     name: "Laise",
     age: 40,
     city: "Brussels",
     country: "Belgium",
     email: "aruna@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529614557/85042438-woman-traveling-in-amsterdam-city.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 21,
     name: "Paulina",
     age: 37,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "paulina@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529615066/pose.jpg',
     interests: [ 'museums', 'coffee', 'books' ],
     isTraveler: false,

   },
   {
     id: 22,
     name: "Iulia",
     age: 26,
     city: "Paris",
     country: "France",
     email: "Iulia@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529615268/10.jpg.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 23,
     name: "Yelena",
     age: 31,
     city: "Stockolm",
     country: "Sweden",
     email: "yelena@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529615746/travel-safe1.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   },
   {
     id: 24,
     name: "Lucio",
     age: 50,
     city: "Brussels",
     country: "Belgium",
     email: "lucio@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529615902/man-on-suitcases_600x700.jpg',
     interests: [ 'yoga', 'dancing', 'fishing' ],
     isTraveler: false,

   }
]
